locals {
  paramstore_creds_path = "/creds/owncloud_test/${random_pet.this.id}"
}

resource random_password owncloud_admin {
  length = 30
}

resource aws_ssm_parameter owncloud_admin_passwd {
  name        = "${local.paramstore_creds_path}/admin_passwd"
  description = "securely storing the password for the OwnCloud admin user"

  type      = "SecureString"
  key_id    = aws_kms_alias.owncloud.target_key_arn
  value     = random_password.owncloud_admin.result
  overwrite = true
}

resource random_password owncloud_db {
  length = 30
}

resource aws_ssm_parameter owncloud_db_passwd {
  name        = "${local.paramstore_creds_path}/db_passwd"
  description = "securely storing the password for the OwnCloud db user"

  type      = "SecureString"
  key_id    = aws_kms_alias.owncloud.target_key_arn
  value     = random_password.owncloud_db.result
  overwrite = true
}

resource random_password owncloud_rds_db {
  length = 30
}

resource aws_ssm_parameter owncloud_ssh_priv_key {
  count = local.custom_ssh_key_material_provided ? 0 : 1

  name        = "${local.paramstore_creds_path}/ssh_priv_key_material"
  description = "SSH private key generated by Terraform for the OwnCloud test activity"

  type      = "SecureString"
  key_id    = aws_kms_alias.owncloud.target_key_arn
  value     = tls_private_key.owncloud[0].private_key_pem
  overwrite = true
}
