FROM nextcloud/server:latest

ENV nextcloud_DOMAIN localhost
ENV nextcloud_DB_TYPE mariadb
ENV nextcloud_DB_NAME nextcloud
ENV nextcloud_DB_USERNAME dbuser
ENV nextcloud_DB_PASSWORD 
ENV nextcloud_DB_HOST nextcloud

EXPOSE 8080

VOLUME ["/mnt/data"]
